### ISSUE TITLE
Fail to open the file in hapdip.js for allele evaluation (rtg vcfeval)

### ISSUE THREAD

**Issue by andreas-wilm** [lh3/rtgeval#1]
Hi Heng,

I would really like to this gives a try, however releases/download/v0.1/rtgevalkit-0.1_x64-linux.tar.bz2 (and the current commit) keep failing on the data-sets I've tried. The weird thing is that the first commands seem to work okay and I made sure all input files exist. The command line in all cases was:

```
/rtgeval.kit/run-eval -s ref/human_g1k_v37.sdf -b $bed $truth $test
```

`$truth` and `$test` are tabix indexed (bgzipped) vcf files.

The error is as follows:

```
Running position-based evaluaton (hapdip distEval)...
Normalizing the truth VCF...
Normalizing the test VCF...
Running allele evaluation (rtg vcfeval --squash-ploidy)...
Running allele evaluation (rtg vcfeval)...
./rtgeval.kit/hapdip.js:472: Error: [File] Fail to open the file
    var file = args.length > getopt.ind? new File(args[getopt.ind]) : new File();
                                                   ^
Error: [File] Fail to open the file
    at b8_qst1 (./rtgeval.kit/hapdip.js:472:52)
    at main (./rtgeval.kit/hapdip.js:1636:26)
    at ./rtgeval.kit/hapdip.js:1650:1
./rtgeval.kit/hapdip.js:472: Error: [File] Fail to open the file
    var file = args.length > getopt.ind? new File(args[getopt.ind]) : new File();
                                                   ^
Error: [File] Fail to open the file
    at b8_qst1 (./rtgeval.kit/hapdip.js:472:52)
    at main (./rtgeval.kit/hapdip.js:1636:26)
    at ./rtgeval.kit/hapdip.js:1650:1
./rtgeval.kit/hapdip.js:472: Error: [File] Fail to open the file
    var file = args.length > getopt.ind? new File(args[getopt.ind]) : new File();
                                                   ^
Error: [File] Fail to open the file
    at b8_qst1 (./rtgeval.kit/hapdip.js:472:52)
    at main (./rtgeval.kit/hapdip.js:1636:26)
    at ./rtgeval.kit/hapdip.js:1650:1
./rtgeval.kit/hapdip.js:472: Error: [File] Fail to open the file
    var file = args.length > getopt.ind? new File(args[getopt.ind]) : new File();
                                                   ^
Error: [File] Fail to open the file
    at b8_qst1 (./rtgeval.kit/hapdip.js:472:52)
    at main (./rtgeval.kit/hapdip.js:1636:26)
    at ./rtgeval.kit/hapdip.js:1650:1
```

Any idea what might be going wrong?

Thanks,
Andreas

**Comment by lh3** [comment]
Could you check if there is a non-empty `PREFIX.vea/fp.vcf.gz`? `PREFIX` should be similar to your input VCF file name. Could you also give me the output of `ls -l PREFIX`? It is strange that `rtg vcfeval --squash-ploidy` completed, but with `--squash-ploidy` failed. Thanks.

**Comment by andreas-wilm** [comment]
Actually, PREFIX.vea/fp.vcf.gz doesn't even exist. PREFIX.vea/vcfeval.log gives a clue:

```
java.io.IOException: VCF header contains multiple field declarations with the same ID=1
##contig=<ID=1>
##contig=<ID=1,length=249250621>
```

This is for PREFIX.test.vcf.gz which has all contig IDs duplicated. This must happen along the way, because the original input test vcf has no duplicated contig lines.

**Comment by lh3** [comment]
I see. That is a bug. I will have a look. Thanks for reporting.

**Comment by lh3** [comment]
Sorry for coming back so late. I have fixed the issue in hapdip.js. You can download the [hapdip.js script](https://raw.githubusercontent.com/lh3/hapdip/552f926874421e245c47d9e37594f380a85ad5ca/hapdip.js) and copy it to `rtgeval.kit`, or re-build rtgeval.kit with:

``` sh
git clone --recursive https://github.com/lh3/rtgeval.git
cd rtgeval; make;
```

**Comment by andreas-wilm** [comment]
Sorry, I still get exactly the same error (just slightly different source code line numbers). I removed all PREFIX files before rerunning. The used commit is c1ae82557958f31d0f78374b5639f9ced8c8c9c1.
Is there anything I could have done wrong?
Is there maybe an alternative hack/workaround to get this running?

**Comment by andreas-wilm** [comment]
Here's a workaround that makes it work. I came across this when I noticed that other tools don't like

```
##contig=<ID=1>
```

as opposed to

```
##contig=<ID=1,length=249250621>
```

Removing all contig entries from the header fixes the problem and rtgeval works smoothly. So I suppose this is not an rtgeval issue but some formatting issue (not sure what's technically wrong with the first contig line though) 

Thanks for your help and thanks for making the wrapper available!

Andreas

PS: contig lines were automatically added by `bcftools norm`
